<a href="https://colab.research.google.com/github/OscarAGzn/Lic.-Oscar-A-Guzman/blob/main/Proyecto_de_Phyton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Analisis de Tuberculosis

In [ ]:
#Propuesta para manipular datos
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pop = pd.read_csv("/content/drive/MyDrive/A/population.csv")
pop.head(5)

       country  year  population
0  Afghanistan  1995    17586073
1  Afghanistan  1996    18415307
2  Afghanistan  1997    19021226
3  Afghanistan  1998    19496836
4  Afghanistan  1999    19987071

In [ ]:
Who = pd.read_csv("/content/drive/MyDrive/A/who.csv")
Who.head(5)

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sn_m014,new_sn_m1524,new_sn_m2534,new_sn_m3544,new_sn_m4554,new_sn_m5564,new_sn_m65,new_sn_f014,new_sn_f1524,new_sn_f2534,new_sn_f3544,new_sn_f4554,new_sn_f5564,new_sn_f65,new_ep_m014,new_ep_m1524,new_ep_m2534,new_ep_m3544,new_ep_m4554,new_ep_m5564,new_ep_m65,new_ep_f014,new_ep_f1524,new_ep_f2534,new_ep_f3544,new_ep_f4554,new_ep_f5564,new_ep_f65,newrel_m014,newrel_m1524,newrel_m2534,newrel_m3544,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
0,Afghanistan,AF,AFG,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AF,AFG,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AF,AFG,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#La Tuberculosis (TB)
###1. Definición y Agente Causal
La tuberculosis es una enfermedad infecciosa y potencialmente grave causada por la bacteria Mycobacterium tuberculosis. Aunque afecta predominantemente a los pulmones (tuberculosis pulmonar), el patógeno tiene la capacidad de diseminarse a través del torrente sanguíneo o el sistema linfático a otros órganos, como los riñones, la columna vertebral y el cerebro (tuberculosis extrapulmonar).

###2. Mecanismo de Transmisión
La vía de contagio es estrictamente aérea. Cuando una persona con la enfermedad activa en los pulmones o la laringe tose, estornuda, habla o canta, expulsa al aire pequeñas gotas (núcleos de Wells) que contienen los bacilos. Para que ocurra el contagio, generalmente se requiere un contacto cercano y prolongado en espacios mal ventilados. Es importante notar que la TB no se transmite por compartir cubiertos, dar la mano o el contacto con superficies.

###3. Infección Latente vs. Enfermedad Activa
Es fundamental distinguir entre dos estados:

Infección de TB Latente: Las bacterias viven en el cuerpo pero el sistema inmunitario las mantiene bajo control. La persona no presenta síntomas, no se siente enferma y no puede contagiar a otros.

Enfermedad de TB Activa: Las bacterias se multiplican porque el sistema inmune no logra contenerlas. La persona presenta síntomas clínicos y puede transmitir la bacteria a los demás.

###4. Cuadro Clínico y Diagnóstico
Los síntomas clásicos de la TB pulmonar incluyen:

Tos persistente (más de 3 semanas), a menudo acompañada de esputo o sangre.

Dolor torácico.

Fatiga crónica y debilidad.

Pérdida de peso involuntaria y anorexia.

Fiebre y sudores nocturnos profusos.

El diagnóstico se confirma mediante pruebas de laboratorio como la baciloscopia (examen de flema), cultivos microbiológicos, pruebas moleculares rápidas (como GeneXpert) y radiografías de tórax para identificar lesiones pulmonares.

###5. Tratamiento y Resistencia a los Fármacos
La tuberculosis es una enfermedad curable. El tratamiento estándar dura entre 6 y 9 meses y requiere la combinación de varios antibióticos (isoniazida, rifampicina, etambutol y pirazinamida).

El mayor desafío actual para la salud pública es la TB Multirresistente (MDR-TB), la cual surge principalmente cuando los pacientes no completan el esquema terapéutico. Esto permite que las bacterias sobrevivan y desarrollen resistencia a los fármacos más potentes, obligando a tratamientos mucho más largos, costosos y con mayores efectos secundarios.

###6. Prevención y Control
La estrategia principal de prevención incluye la vacunación con BCG en recién nacidos (que protege contra formas graves como la meningitis tuberculosa) y, sobre todo, la detección temprana y el tratamiento oportuno de los casos activos para cortar la cadena de transmisión en la comunidad.

#Limpieza y manipulacion de datos

###Explorar losvalores nulos/faltantes/NA

In [ ]:
# Cuantos valores faltantes hay por columna?
Who.isna().sum()

country            0
iso2              34
iso3               0
year               0
new_sp_m014     4067
new_sp_m1524    4031
new_sp_m2534    4034
new_sp_m3544    4021
new_sp_m4554    4017
new_sp_m5564    4022
new_sp_m65      4031
new_sp_f014     4066
new_sp_f1524    4046
new_sp_f2534    4040
new_sp_f3544    4041
new_sp_f4554    4036
new_sp_f5564    4045
new_sp_f65      4043
new_sn_m014     6195
new_sn_m1524    6210
new_sn_m2534    6218
new_sn_m3544    6215
new_sn_m4554    6213
new_sn_m5564    6219
new_sn_m65      6220
new_sn_f014     6200
new_sn_f1524    6218
new_sn_f2534    6224
new_sn_f3544    6220
new_sn_f4554    6222
new_sn_f5564    6223
new_sn_f65      6221
new_ep_m014     6202
new_ep_m1524    6214
new_ep_m2534    6220
new_ep_m3544    6216
new_ep_m4554    6220
new_ep_m5564    6225
new_ep_m65      6222
new_ep_f014     6208
new_ep_f1524    6219
new_ep_f2534    6219
new_ep_f3544    6219
new_ep_f4554    6223
new_ep_f5564    6223
new_ep_f65      6226
newrel_m014     7050
newrel_m1524    7058
newrel_m2534    7057
newrel_m3544    7056
newrel_m4554    7056
newrel_m5564    7055
newrel_m65      7058
newrel_f014     7050
newrel_f1524    7056
newrel_f2534    7058
newrel_f3544    7057
newrel_f4554    7057
newrel_f5564    7057
newrel_f65      7055
dtype: int64

In [ ]:
#Expplorar los valores faltantes de de la columna iso2
Who[Who.iso2.isna()]

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sn_m014,new_sn_m1524,new_sn_m2534,new_sn_m3544,new_sn_m4554,new_sn_m5564,new_sn_m65,new_sn_f014,new_sn_f1524,new_sn_f2534,new_sn_f3544,new_sn_f4554,new_sn_f5564,new_sn_f65,new_ep_m014,new_ep_m1524,new_ep_m2534,new_ep_m3544,new_ep_m4554,new_ep_m5564,new_ep_m65,new_ep_f014,new_ep_f1524,new_ep_f2534,new_ep_f3544,new_ep_f4554,new_ep_f5564,new_ep_f65,newrel_m014,newrel_m1524,newrel_m2534,newrel_m3544,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
4369,Namibia,NaN,NAM,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4370,Namibia,NaN,NAM,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4371,Namibia,NaN,NAM,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4372,Namibia,NaN,NAM,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4373,Namibia,NaN,NAM,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4374,Namibia,NaN,NAM,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4375,Namibia,NaN,NAM,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4376,Namibia,NaN,NAM,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4377,Namibia,NaN,NAM,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4378,Namibia,NaN,NAM,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4379,Namibia,NaN,NAM,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4380,Namibia,NaN,NAM,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4381,Namibia,NaN,NAM,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4382,Namibia,NaN,NAM,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4383,Namibia,NaN,NAM,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4384,Namibia,NaN,NAM,1995,0.0,68.0,235.0,113.0,55.0,21.0,6.0,5.0,49.0,78.0,50.0,16.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4385,Namibia,NaN,NAM,1996,16.0,205.0,613.0,472.0,230.0,137.0,101.0,17.0,249.0,330.0,245.0,87.0,72.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4386,Namibia,NaN,NAM,1997,18.0,232.0,791.0,479.0,296.0,161.0,93.0,23.0,249.0,401.0,275.0,104.0,56.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4387,Namibia,NaN,NAM,1998,21.0,270.0,816.0,541.0,267.0,148.0,111.0,34.0,300.0,536.0,310.0,117.0,62.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,Namibia,NaN,NAM,1999,20.0,247.0,908.0,613.0,260.0,135.0,110.0,25.0,339.0,540.0,336.0,114.0,77.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,Namibia,NaN,NAM,2000,18.0,269.0,874.0,665.0,300.0,147.0,81.0,16.0,352.0,654.0,348.0,161.0,76.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,Namibia,NaN,NAM,2001,20.0,322.0,993.0,732.0,318.0,150.0,116.0,32.0,394.0,729.0,404.0,168.0,91.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,Namibia,NaN,NAM,2002,19.0,301.0,1033.0,750.0,326.0,146.0,96.0,42.0,357.0,795.0,484.0,182.0,91.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4392,Namibia,NaN,NAM,2003,31.0,364.0,1109.0,838.0,419.0,196.0,108.0,47.0,451.0,927.0,571.0,216.0,108.0,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4393,Namibia,NaN,NAM,2004,31.0,319.0,1092.0,866.0,371.0,159.0,131.0,30.0,400.0,819.0,554.0,203.0,106.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4394,Namibia,NaN,NAM,2005,98.0,355.0,1027.0,874.0,365.0,146.0,120.0,105.0,399.0,809.0,525.0,213.0,95.0,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4395,Namibia,NaN,NAM,2006,86.0,347.0,1052.0,799.0,386.0,174.0,146.0,74.0,485.0,875.0,521.0,239.0,92.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4396,Namibia,NaN,NAM,2007,57.0,370.0,1018.0,786.0,346.0,149.0,120.0,69.0,417.0,826.0,513.0,242.0,102.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4397,Namibia,NaN,NAM,2008,30.0,387.0,1033.0,757.0,346.0,149.0,132.0,73.0,466.0,702.0,437.0,226.0,110.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4398,Namibia,NaN,NAM,2009,41.0,357.0,936.0,689.0,348.0,166.0,121.0,84.0,384.0,678.0,407.0,214.0,97.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4399,Namibia,NaN,NAM,2010,36.0,359.0,852.0,680.0,287.0,146.0,126.0,67.0,429.0,685.0,382.0,206.0,122.0,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4400,Namibia,NaN,NAM,2011,48.0,337.0,844.0,660.0,361.0,152.0,138.0,78.0,427.0,653.0,410.0,185.0,100.0,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4401,Namibia,NaN,NAM,2012,61.0,358.0,810.0,686.0,292.0,157.0,137.0,81.0,394.0,582.0,396.0,198.0,84.0,97.0,386.0,153.0,477.0,516.0,268.0,162.0,135.0,339.0,200.0,379.0,306.0,183.0,98.0,90.0,180.0,126.0,228.0,261.0,138.0,46.0,55.0,163.0,116.0,219.0,177.0,84.0,25.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4402,Namibia,NaN,NAM,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,612.0,1496.0,1404.0,723.0,392.0,309.0,491.0,688.0,1137.0,747.0,408.0,220.0,202.0

In [ ]:
#cuantos valores faltantes hay por columna?
Who.isna().sum()

country            0
iso2              34
iso3               0
year               0
new_sp_m014     4067
new_sp_m1524    4031
new_sp_m2534    4034
new_sp_m3544    4021
new_sp_m4554    4017
new_sp_m5564    4022
new_sp_m65      4031
new_sp_f014     4066
new_sp_f1524    4046
new_sp_f2534    4040
new_sp_f3544    4041
new_sp_f4554    4036
new_sp_f5564    4045
new_sp_f65      4043
new_sn_m014     6195
new_sn_m1524    6210
new_sn_m2534    6218
new_sn_m3544    6215
new_sn_m4554    6213
new_sn_m5564    6219
new_sn_m65      6220
new_sn_f014     6200
new_sn_f1524    6218
new_sn_f2534    6224
new_sn_f3544    6220
new_sn_f4554    6222
new_sn_f5564    6223
new_sn_f65      6221
new_ep_m014     6202
new_ep_m1524    6214
new_ep_m2534    6220
new_ep_m3544    6216
new_ep_m4554    6220
new_ep_m5564    6225
new_ep_m65      6222
new_ep_f014     6208
new_ep_f1524    6219
new_ep_f2534    6219
new_ep_f3544    6219
new_ep_f4554    6223
new_ep_f5564    6223
new_ep_f65      6226
newrel_m014     7050
newrel_m1524    7058
newrel_m2534    7057
newrel_m3544    7056
newrel_m4554    7056
newrel_m5564    7055
newrel_m65      7058
newrel_f014     7050
newrel_f1524    7056
newrel_f2534    7058
newrel_f3544    7057
newrel_f4554    7057
newrel_f5564    7057
newrel_f65      7055
dtype: int64

In [ ]:
# Explorar los valores faltantes en la columna iso2
Who[Who.iso2.isna()]

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,new_sp_m65,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sn_m014,new_sn_m1524,new_sn_m2534,new_sn_m3544,new_sn_m4554,new_sn_m5564,new_sn_m65,new_sn_f014,new_sn_f1524,new_sn_f2534,new_sn_f3544,new_sn_f4554,new_sn_f5564,new_sn_f65,new_ep_m014,new_ep_m1524,new_ep_m2534,new_ep_m3544,new_ep_m4554,new_ep_m5564,new_ep_m65,new_ep_f014,new_ep_f1524,new_ep_f2534,new_ep_f3544,new_ep_f4554,new_ep_f5564,new_ep_f65,newrel_m014,newrel_m1524,newrel_m2534,newrel_m3544,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
4369,Namibia,NaN,NAM,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4370,Namibia,NaN,NAM,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4371,Namibia,NaN,NAM,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4372,Namibia,NaN,NAM,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4373,Namibia,NaN,NAM,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4374,Namibia,NaN,NAM,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4375,Namibia,NaN,NAM,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4376,Namibia,NaN,NAM,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4377,Namibia,NaN,NAM,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4378,Namibia,NaN,NAM,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4379,Namibia,NaN,NAM,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4380,Namibia,NaN,NAM,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4381,Namibia,NaN,NAM,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4382,Namibia,NaN,NAM,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4383,Namibia,NaN,NAM,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4384,Namibia,NaN,NAM,1995,0.0,68.0,235.0,113.0,55.0,21.0,6.0,5.0,49.0,78.0,50.0,16.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4385,Namibia,NaN,NAM,1996,16.0,205.0,613.0,472.0,230.0,137.0,101.0,17.0,249.0,330.0,245.0,87.0,72.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4386,Namibia,NaN,NAM,1997,18.0,232.0,791.0,479.0,296.0,161.0,93.0,23.0,249.0,401.0,275.0,104.0,56.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4387,Namibia,NaN,NAM,1998,21.0,270.0,816.0,541.0,267.0,148.0,111.0,34.0,300.0,536.0,310.0,117.0,62.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,Namibia,NaN,NAM,1999,20.0,247.0,908.0,613.0,260.0,135.0,110.0,25.0,339.0,540.0,336.0,114.0,77.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,Namibia,NaN,NAM,2000,18.0,269.0,874.0,665.0,300.0,147.0,81.0,16.0,352.0,654.0,348.0,161.0,76.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,Namibia,NaN,NAM,2001,20.0,322.0,993.0,732.0,318.0,150.0,116.0,32.0,394.0,729.0,404.0,168.0,91.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,Namibia,NaN,NAM,2002,19.0,301.0,1033.0,750.0,326.0,146.0,96.0,42.0,357.0,795.0,484.0,182.0,91.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4392,Namibia,NaN,NAM,2003,31.0,364.0,1109.0,838.0,419.0,196.0,108.0,47.0,451.0,927.0,571.0,216.0,108.0,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4393,Namibia,NaN,NAM,2004,31.0,319.0,1092.0,866.0,371.0,159.0,131.0,30.0,400.0,819.0,554.0,203.0,106.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4394,Namibia,NaN,NAM,2005,98.0,355.0,1027.0,874.0,365.0,146.0,120.0,105.0,399.0,809.0,525.0,213.0,95.0,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4395,Namibia,NaN,NAM,2006,86.0,347.0,1052.0,799.0,386.0,174.0,146.0,74.0,485.0,875.0,521.0,239.0,92.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4396,Namibia,NaN,NAM,2007,57.0,370.0,1018.0,786.0,346.0,149.0,120.0,69.0,417.0,826.0,513.0,242.0,102.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4397,Namibia,NaN,NAM,2008,30.0,387.0,1033.0,757.0,346.0,149.0,132.0,73.0,466.0,702.0,437.0,226.0,110.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4398,Namibia,NaN,NAM,2009,41.0,357.0,936.0,689.0,348.0,166.0,121.0,84.0,384.0,678.0,407.0,214.0,97.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4399,Namibia,NaN,NAM,2010,36.0,359.0,852.0,680.0,287.0,146.0,126.0,67.0,429.0,685.0,382.0,206.0,122.0,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4400,Namibia,NaN,NAM,2011,48.0,337.0,844.0,660.0,361.0,152.0,138.0,78.0,427.0,653.0,410.0,185.0,100.0,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4401,Namibia,NaN,NAM,2012,61.0,358.0,810.0,686.0,292.0,157.0,137.0,81.0,394.0,582.0,396.0,198.0,84.0,97.0,386.0,153.0,477.0,516.0,268.0,162.0,135.0,339.0,200.0,379.0,306.0,183.0,98.0,90.0,180.0,126.0,228.0,261.0,138.0,46.0,55.0,163.0,116.0,219.0,177.0,84.0,25.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4402,Namibia,NaN,NAM,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,612.0,1496.0,1404.0,723.0,392.0,309.0,491.0,688.0,1137.0,747.0,408.0,220.0,202.0

In [ ]:
# Los valores NA se debe a que el iso2 de Namibia es "NA", y pandas lo tomo como un vaor faltante
Who.loc[Who.country == "Namibia", "iso2"] = "NA"

In [ ]:
#Las demas columnas de casos con valores faltantes van a tener un valor faltante de 0
Who.fillna(0, inplace=True)

In [ ]:
# Cuantos valores faltantes hay por columna en la tabla de pop?
pop.isna().sum()

country       0
year          0
population    0
dtype: int64

In [ ]:
#Cono puedo convertir columnas en filas utilizando pandas? = existe la funcion melt()
#Buscar la funcion melt en la documentacion oficial
# Tengo una tabla de esta estructura
who2=Who.melt(id_vars=["country", "iso2","iso3","year"])
who2.head(10)

       country iso2 iso3  year     variable  value
0  Afghanistan   AF  AFG  1980  new_sp_m014    0.0
1  Afghanistan   AF  AFG  1981  new_sp_m014    0.0
2  Afghanistan   AF  AFG  1982  new_sp_m014    0.0
3  Afghanistan   AF  AFG  1983  new_sp_m014    0.0
4  Afghanistan   AF  AFG  1984  new_sp_m014    0.0
5  Afghanistan   AF  AFG  1985  new_sp_m014    0.0
6  Afghanistan   AF  AFG  1986  new_sp_m014    0.0
7  Afghanistan   AF  AFG  1987  new_sp_m014    0.0
8  Afghanistan   AF  AFG  1988  new_sp_m014    0.0
9  Afghanistan   AF  AFG  1989  new_sp_m014    0.0

In [ ]:
# Crar una columna que contenga el genero (masculinon o femenino)
#Crear una fncion de Phyton que contenga las reglas
def asignar_genero(valor):
  if"m" in valor:
    return "Masculino"
  else:
    return "Femenino"

In [ ]:
who2['genero'] = who2['variable'].apply(asignar_genero)
who2.head(10)

       country iso2 iso3  year     variable  value     genero
0  Afghanistan   AF  AFG  1980  new_sp_m014    0.0  Masculino
1  Afghanistan   AF  AFG  1981  new_sp_m014    0.0  Masculino
2  Afghanistan   AF  AFG  1982  new_sp_m014    0.0  Masculino
3  Afghanistan   AF  AFG  1983  new_sp_m014    0.0  Masculino
4  Afghanistan   AF  AFG  1984  new_sp_m014    0.0  Masculino
5  Afghanistan   AF  AFG  1985  new_sp_m014    0.0  Masculino
6  Afghanistan   AF  AFG  1986  new_sp_m014    0.0  Masculino
7  Afghanistan   AF  AFG  1987  new_sp_m014    0.0  Masculino
8  Afghanistan   AF  AFG  1988  new_sp_m014    0.0  Masculino
9  Afghanistan   AF  AFG  1989  new_sp_m014    0.0  Masculino

In [ ]:
# the method of diagnosis (rel = relapse, sn = negative pulmonary smear, sp = positive pulmonary smear, ep = extrapulmonary)
def asignar_metodo(valor):
  if "rel" in valor:
    return "relapse"
  elif "sn" in valor:
    return "negative pulmonary smear"
  elif "sp" in valor:
    return "positive pulmonary smear"
  elif "ep" in valor:
    return "extrapulmonary"
  else:
    return "to define"

In [ ]:
who2["metodo"] = who2["variable"].apply(asignar_metodo)
who2.head(10)

,country,iso2,iso3,year,variable,value,genero,metodo
0,Afghanistan,AF,AFG,1980,new_sp_m014,0.0,Masculino,positive pulmonary smear
1,Afghanistan,AF,AFG,1981,new_sp_m014,0.0,Masculino,positive pulmonary smear
2,Afghanistan,AF,AFG,1982,new_sp_m014,0.0,Masculino,positive pulmonary smear
3,Afghanistan,AF,AFG,1983,new_sp_m014,0.0,Masculino,positive pulmonary smear
4,Afghanistan,AF,AFG,1984,new_sp_m014,0.0,Masculino,positive pulmonary smear
5,Afghanistan,AF,AFG,1985,new_sp_m014,0.0,Masculino,positive pulmonary smear
6,Afghanistan,AF,AFG,1986,new_sp_m014,0.0,Masculino,positive pulmonary smear
7,Afghanistan,AF,AFG,1987,new_sp_m014,0.0,Masculino,positive pulmonary smear
8,Afghanistan,AF,AFG,1988,new_sp_m014,0.0,Masculino,positive pulmonary smear
9,Afghanistan,AF,AFG,1989,new_sp_m014,0.0,Masculino,positive pulmonary smear

In [ ]:
# age group (014 = 0-14 yrs of age, 1524 = 15-24, 2534 = 25-34, 3544 = 35-44 years of age, 4554 = 45-54, 5564 = 55-64, 65 = 65 years or older).
def asignar_grupoedad(valor):
  if "014" in valor:
    return "0-14"
  elif "1524" in valor:
    return "15-24"
  elif "2534" in valor:
    return "25-34"
  elif "3544" in valor:
    return "35-44"
  elif "4554" in valor:
    return "45-54"
  elif "5564" in valor:
    return "55-64"
  else:
    return "65+"

In [ ]:
who2["grupoeddad"] = who2["variable"].apply(asignar_grupoedad)
who2.head(10)

,country,iso2,iso3,year,variable,value,genero,metodo,grupoeddad
0,Afghanistan,AF,AFG,1980,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
1,Afghanistan,AF,AFG,1981,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
2,Afghanistan,AF,AFG,1982,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
3,Afghanistan,AF,AFG,1983,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
4,Afghanistan,AF,AFG,1984,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
5,Afghanistan,AF,AFG,1985,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
6,Afghanistan,AF,AFG,1986,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
7,Afghanistan,AF,AFG,1987,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
8,Afghanistan,AF,AFG,1988,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
9,Afghanistan,AF,AFG,1989,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14

In [ ]:
who2.drop(columns=["variable"], inplace=True)

In [ ]:
who2.rename(columns={"value":"cases"}, inplace=True)

In [ ]:
who2.head(10)

,country,iso2,iso3,year,cases,genero,metodo,grupoeddad
0,Afghanistan,AF,AFG,1980,0.0,Masculino,positive pulmonary smear,0-14
1,Afghanistan,AF,AFG,1981,0.0,Masculino,positive pulmonary smear,0-14
2,Afghanistan,AF,AFG,1982,0.0,Masculino,positive pulmonary smear,0-14
3,Afghanistan,AF,AFG,1983,0.0,Masculino,positive pulmonary smear,0-14
4,Afghanistan,AF,AFG,1984,0.0,Masculino,positive pulmonary smear,0-14
5,Afghanistan,AF,AFG,1985,0.0,Masculino,positive pulmonary smear,0-14
6,Afghanistan,AF,AFG,1986,0.0,Masculino,positive pulmonary smear,0-14
7,Afghanistan,AF,AFG,1987,0.0,Masculino,positive pulmonary smear,0-14
8,Afghanistan,AF,AFG,1988,0.0,Masculino,positive pulmonary smear,0-14
9,Afghanistan,AF,AFG,1989,0.0,Masculino,positive pulmonary smear,0-14

In [ ]:
# Traer el dato de la poblacion total
df = pd.merge(who2, pop, on=["country", "year"], how="inner")
df.head(10)

,country,iso2,iso3,year,cases,genero,metodo,grupoeddad,population
0,Afghanistan,AF,AFG,1995,0.0,Masculino,positive pulmonary smear,0-14,17586073
1,Afghanistan,AF,AFG,1996,0.0,Masculino,positive pulmonary smear,0-14,18415307
2,Afghanistan,AF,AFG,1997,0.0,Masculino,positive pulmonary smear,0-14,19021226
3,Afghanistan,AF,AFG,1998,30.0,Masculino,positive pulmonary smear,0-14,19496836
4,Afghanistan,AF,AFG,1999,8.0,Masculino,positive pulmonary smear,0-14,19987071
5,Afghanistan,AF,AFG,2000,52.0,Masculino,positive pulmonary smear,0-14,20595360
6,Afghanistan,AF,AFG,2001,129.0,Masculino,positive pulmonary smear,0-14,21347782
7,Afghanistan,AF,AFG,2002,90.0,Masculino,positive pulmonary smear,0-14,22202806
8,Afghanistan,AF,AFG,2003,127.0,Masculino,positive pulmonary smear,0-14,23116142
9,Afghanistan,AF,AFG,2004,139.0,Masculino,positive pulmonary smear,0-14,24018682

In [ ]:
import os

# Como guardar la tabla "df" como un archivo csv
df.to_csv("tuberculosis.csv") # se guarda en la carpeta de la sesion

# Define the directory path
drive_data_path = "/content/drive/MyDrive/data"

# Create the directory if it does not exist
os.makedirs(drive_data_path, exist_ok=True)

df.to_csv(f"{drive_data_path}/tuberculosis.csv") # se guarda en el drive

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go